### PR TITLE
fix load game crash when no save files are present

### LINKED ISSUE #222: Runtime error when loading a save game when there is no save game

### PR DESCRIPTION
**Pull request by Philbywhizz**
Fixes #222 

Changes proposed in this pull request.
- This codes checks for the game .dat files, and if they don't exist notify the user by the new world being created anyway. 

It's probably not the most elegant solution but it works :)

Happy for feedback.

### CODE REVIEW

**Comment by togfoxy** [comment]
Sorry Phil. Mad's PR came first and your globals need to be updated now. I'm sure it will be easy to do.

**Comment by togfoxy** [comment]
This is the next PR and is ready to merge when the conflicts are sorted. You can see the global names need to be updated.

**Comment by togfoxy** [comment]
Midnight. Bedtime. Whoever gets to resolve this first can feel free to merge it immediately. The change is minor so zero risk. Thx.

File: source/functions.lua [hunk 1]
```diff
@@ -120,19 +120,38 @@ function functions.LoadGame()
...
     local savefile
     local contents
+	local size
+	local error = false
 
     savefile = savedir .. "/" .. "landers.dat"
-    contents, _ = nativefs.read( savefile)
-    garrLanders = bitser.loads(contents)
+
+	if love.filesystem.getInfo(savefile) ~= nil then
```
Comment (MadByteDE) [inline source/functions.lua:128]: This will result in error being true when the file has been found. Better just change to
```lua
if not love.filesystem.getInfo(savefile) then
```
 not double negate the value by acident.

**Review by MadByteDE — CHANGES_REQUESTED** [review]
There is an issue with the file check.. see comment.

**Comment by MadByteDE** [comment]
sorry, I tested it but didn't realized that the code still is flawed because previously it would always show the "cant load game" message, and now it won't load the game because there's already a file found. I've reverted to the previous behaviour, but it's still bugged that way. I shouldn't have merged it but I believed it would be fixed with the changes. I'll go ahead and fix it so that everything works as expected to have a working code base in main.

File: source/functions.lua (hunk 1 above)
Comment (MadByteDE) [reply source/functions.lua]: I was wrong. all good :heart:

File: source/functions.lua [hunk 2]
```diff
@@ -120,19 +120,38 @@ function functions.LoadGame()
...
     local contents
+	local size
+	local error = false
 
     savefile = savedir .. "/" .. "landers.dat"
-    contents, _ = Nativefs.read( savefile)
-    LANDERS = Bitser.loads(contents)
+
+	if not love.filesystem.getInfo(savefile) then
+	    contents, size = nativefs.read(savefile)
```
Comment (MadByteDE) [inline source/functions.lua:129]: Since `love.filesystem.getInfo` is not searching for files inside the source directory, error always was true, at least for me.
I pushed a commit to main (4bd00a5f024c4b327ecf1d1abbb21c970217feb1) that changed `love.filesystem.getInfo` for `Nativefs.getInfo`. 

It also changes the old globals to the new format.

**Comment by togfoxy** [comment]
Thanks for spring that out!
